# Generated by Django 3.2.9 on 2021-11-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialLinks', '0002_auto_20211120_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='csseditor',
            name='link_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
