# Generated by Django 3.2.9 on 2021-11-24 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialLinks', '0006_csseditor_link_hover_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='styleEditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='Home', max_length=20)),
                ('Link_Color', models.CharField(default='#000000', max_length=7)),
                ('Link_Font_Style', models.CharField(default='Brush Script MT', max_length=15)),
                ('Link_Background_Color', models.CharField(default='#F5F5F5', max_length=7)),
                ('Link_Hover_Color', models.CharField(default='#000000', max_length=7)),
            ],
        ),
        migrations.RenameModel(
            old_name='backgroundImage',
            new_name='backgroundPic',
        ),
        migrations.RenameModel(
            old_name='Image',
            new_name='profilePic',
        ),
        migrations.DeleteModel(
            name='cssEditor',
        ),
    ]
