# Generated by Django 3.2.9 on 2021-12-01 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialLinks', '0008_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='linkText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkText1', models.CharField(default='Instagram', max_length=100)),
                ('linkText2', models.CharField(default='Facebook', max_length=100)),
                ('linkText3', models.CharField(default='Namecheap', max_length=100)),
                ('linkText4', models.CharField(default='Email', max_length=100)),
                ('linkText5', models.CharField(default='Contact Me', max_length=100)),
                ('linkText6', models.CharField(default='Link 6', max_length=100)),
                ('linkText7', models.CharField(default='Link 7', max_length=100)),
            ],
        ),
    ]
