# Generated by Django 3.2.9 on 2021-11-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialLinks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csseditor',
            old_name='linkcolor',
            new_name='link_color',
        ),
        migrations.AddField(
            model_name='csseditor',
            name='link_bc',
            field=models.CharField(default='#F5F5F5', max_length=7),
        ),
        migrations.AddField(
            model_name='csseditor',
            name='link_font',
            field=models.CharField(default='Brush Script MT', max_length=15),
        ),
    ]
